version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.0

    volumes:
      - redis_data:/data
    networks:
      - app-network

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api-gateway:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - KAFKA_BROKER=kafka:29092
      - REDIS_HOST=redis
      - REGEX_PATTERN=${REGEX_PATTERN:-^[A-Za-z0-9]+$}
      - VALIDATION_DELAY=${VALIDATION_DELAY:-1000}
    depends_on:
      - mongodb
      - kafka
      - redis
    networks:
      - app-network

  validation-service:
    build:
      context: ./backend/validation-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - KAFKA_BROKER=kafka:29092
      - REDIS_HOST=redis
      - REGEX_PATTERN=${REGEX_PATTERN:-^[A-Za-z0-9]+$}
      - VALIDATION_DELAY=${VALIDATION_DELAY:-1000}
    depends_on:
      - mongodb
      - kafka
      - redis
    volumes:
      - ./backend/validation-service:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "61234:5173"
    environment:
      - VITE_API_URL=http://localhost:3000 # For browser access
      - VITE_WS_URL=ws://localhost:3000 # For browser access
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
